name: launcher_icon
description: Flutter app's launcher icon.
version: 0.0.1
maintainer: Emin Tolgahan Polat
homepage: https://github.com/emintolgahanpolat
repository: https://github.com/emintolgahanpolat
issue_tracker: https://github.com/emintolgahanpolat

dependencies:
  args: ^2.3.2
  collection: ^1.18.0
  image: ^4.0.15
  path: ^1.8.2
  yaml: ^3.1.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  test: ^1.23.1
